import dspy
from dspy.teleprompt import GEPA
import json
import logging
from typing import ClassVar
from pydantic import BaseModel, Field

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ── LMs ───────────────────────────────────────────────────────────────────────

lm = dspy.LM("gemini/gemini-2.0-flash")
reflection_lm = dspy.LM("gemini/gemini-2.5-pro", temperature=1.0, max_tokens=8000)
dspy.configure(lm=lm)

# ── Signatures ────────────────────────────────────────────────────────────────

class SARNarrativeGenerator(dspy.Signature):
    """Generate the narrative section of a Suspicious Activity Report (SAR) for FinCEN."""
    alert_type: str = dspy.InputField(desc="Type of suspicion: structuring, layering, elder_exploitation, etc.")
    transaction_logs: str = dspy.InputField(desc="Raw transaction data, dates, amounts, and counter-parties")
    customer_profile: str = dspy.InputField(desc="Customer KYC data: occupation, age, expected activity")
    sar_narrative: str = dspy.OutputField(desc="Chronological, compliant, and objective narrative for regulators")


# ── Pydantic output models ────────────────────────────────────────────────────

class ComplianceCriterion(BaseModel):
    score: float = Field(ge=0, le=10, description="Score between 0 and 10")
    issues: str = Field(description="Specific deficiencies found")
    edits: str = Field(description="Required edits")


class ComplianceOutput(BaseModel):
    accuracy: ComplianceCriterion
    chronology: ComplianceCriterion
    five_ws: ComplianceCriterion
    compliance: ComplianceCriterion
    objectivity: ComplianceCriterion
    overall_score: float = Field(ge=0, le=10, description="Weighted overall score 0–10")
    summary_feedback: str = Field(description="Summary of the feedback")

    WEIGHTS: ClassVar[dict[str, float]] = {"accuracy": 0.30, "compliance": 0.25, "five_ws": 0.20,
                                            "chronology": 0.15, "objectivity": 0.10}

    def weighted_score(self) -> float:
        """Recompute the weighted score locally as a sanity-check."""
        return (
            self.accuracy.score    * self.WEIGHTS["accuracy"]
            + self.compliance.score  * self.WEIGHTS["compliance"]
            + self.five_ws.score     * self.WEIGHTS["five_ws"]
            + self.chronology.score  * self.WEIGHTS["chronology"]
            + self.objectivity.score * self.WEIGHTS["objectivity"]
        )


class ComplianceReview(dspy.Signature):
    """
    Evaluate the SAR Narrative on these critical regulatory criteria:

    1. ACCURACY    (weight 0.30): Are detailed amounts, dates, and account numbers cited correctly?
    2. COMPLIANCE  (weight 0.25): Does it use correct terminology (e.g., 'structuring', 'no apparent business purpose')?
    3. FIVE_WS     (weight 0.20): Does it answer Who, What, Where, When, and Why clearly?
    4. CHRONOLOGY  (weight 0.15): Is the sequence of events logical and easy to follow?
    5. OBJECTIVITY (weight 0.10): Is the tone fact-based and professional (avoiding opinions/speculation)?

    For each criterion provide: score (0–10), specific deficiencies, and required edits.
    Compute overall_score as the weighted sum of the five criteria using the weights above.
    """
    alert_type: str = dspy.InputField(desc="The type of suspicious activity alert")
    data: str = dspy.InputField(desc="Transaction logs and related data")
    profile: str = dspy.InputField(desc="Customer profile and KYC information")
    expected_narrative: str = dspy.InputField(desc="Ground-truth high-quality narrative")
    generated_narrative: str = dspy.InputField(desc="Narrative generated by the agent to be evaluated")
    compliance_review: ComplianceOutput = dspy.OutputField(desc="Detailed compliance review")

# ── Judge (initialised once) ──────────────────────────────────────────────────

_judge_lm = dspy.LM("gemini/gemini-2.5-pro", temperature=0.3)
_judge = dspy.ChainOfThought(ComplianceReview)


def compliance_officer_judge(
    gold, pred, trace=None, pred_name=None, pred_trace=None
) -> float | dict:
    """
    LLM-as-judge metric simulating a Senior Compliance Officer.
    Returns a dict when pred_name is set (GEPA named-metric mode),
    otherwise returns a plain float for standard metric mode.
    """
    with dspy.context(lm=_judge_lm):
        assessment = _judge(
            alert_type=gold.alert_type,
            data=gold.transaction_logs,
            profile=gold.customer_profile,
            expected_narrative=gold.sar_narrative,
            generated_narrative=pred.sar_narrative,
        )

    evaluation: ComplianceOutput = assessment.compliance_review
    # Use the locally recomputed weighted score as the authoritative value
    score = evaluation.weighted_score() / 10.0
    feedback = evaluation.model_dump_json(indent=2)

    logger.info("Judge score: %.3f", score)

    if pred_name is not None:
        return {"score": score, "feedback": feedback}
    return score

# ── Agent ─────────────────────────────────────────────────────────────────────

class FinTechComplianceAgent(dspy.Module):
    def __init__(self):
        super().__init__()
        self.generator = dspy.ChainOfThought(SARNarrativeGenerator)

    def forward(self, alert_type, transaction_logs, customer_profile):
        return self.generator(
            alert_type=alert_type,
            transaction_logs=transaction_logs,
            customer_profile=customer_profile,
        )

# ── Data helpers ──────────────────────────────────────────────────────────────

def load_dataset(path: str, max_train: int | None = None, max_val: int | None = None) -> tuple[list, list]:
    with open(path, "r") as f:
        data = json.load(f)

    def make(split, limit):
        raw = data[split]
        if not isinstance(raw, list):
            raise ValueError(f"Expected data['{split}'] to be a list, got {type(raw).__name__}. Check your JSON structure.")
        items = raw[:limit] if limit else raw
        return [
            dspy.Example(**x).with_inputs("alert_type", "transaction_logs", "customer_profile")
            for x in items
        ]

    return make("train", max_train), make("val", max_val)

# ── Training ──────────────────────────────────────────────────────────────────

def train(
    data_path: str = "compliance_data.json",
    save_path: str = "compiled_agent.json",
    max_train: int | None = None,
    max_val: int | None = None,
    quick_run: bool = False,
) -> FinTechComplianceAgent:
    trainset, valset = load_dataset(data_path, max_train=max_train, max_val=max_val)
    logger.info("Loaded %d train / %d val examples", len(trainset), len(valset))
    if len(trainset) < 2 or len(valset) < 1:
        raise ValueError(f"Dataset too small: need ≥2 train and ≥1 val, got {len(trainset)}/{len(valset)}.")

    optimizer = GEPA(
        metric=compliance_officer_judge,
        auto="light" if not quick_run else None,
        max_metric_calls=50 if quick_run else None,
        reflection_lm=reflection_lm,
        reflection_minibatch_size=1,
        use_merge=True,
        track_stats=True,
        seed=42,
    )

    logger.info("Starting GEPA optimisation…")
    compiled_agent = optimizer.compile(
        student=FinTechComplianceAgent(),
        trainset=trainset,
        valset=valset,
    )

    compiled_agent.save(save_path)
    logger.info("Compiled agent saved to %s", save_path)
    return compiled_agent

# ── Evaluation ────────────────────────────────────────────────────────────────

def evaluate(agent: FinTechComplianceAgent, data_path: str = "compliance_data.json") -> None:
    _, valset = load_dataset(data_path)
    evaluator = dspy.Evaluate(devset=valset, metric=compliance_officer_judge, display_progress=True)
    score = evaluator(agent)
    logger.info("Validation score: %.3f", score)

# ── Inference ─────────────────────────────────────────────────────────────────

def run_inference(agent: FinTechComplianceAgent, test_case: dict) -> str:
    result = agent(
        alert_type=test_case["alert_type"],
        transaction_logs=test_case["transaction_logs"],
        customer_profile=test_case["customer_profile"],
    )
    logger.info("Alert type: %s", test_case["alert_type"])
    logger.info("Generated SAR Narrative:\n%s", result.sar_narrative)
    return result.sar_narrative

# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="SAR Compliance Agent")
    parser.add_argument("--mode", choices=["train", "eval", "infer"], default="train")
    parser.add_argument("--data", default="compliance_data.json")
    parser.add_argument("--model", default="compiled_agent.json")
    parser.add_argument("--test", action="store_true", help="Use a tiny subset (5 train / 3 val) for a quick smoke-test")
    args = parser.parse_args()

    max_train, max_val = (5, 3) if args.test else (None, None)

    if args.mode == "train":
        train(data_path=args.data, save_path=args.model, max_train=max_train, max_val=max_val, quick_run=args.test)

    elif args.mode == "eval":
        agent = FinTechComplianceAgent()
        agent.load(args.model)
        evaluate(agent, data_path=args.data)

    elif args.mode == "infer":
        agent = FinTechComplianceAgent()
        agent.load(args.model)
        test_case = {
            "alert_type": "elder_exploitation",
            "transaction_logs": "Customer (age 82) withdrew $50,000 cash. Accompanied by non-relative 'Nephew'. Customer appeared confused.",
            "customer_profile": "Retired teacher. Fixed income. Never withdraws >$500.",
        }
        run_inference(agent, test_case)